
spring:
#数据源配置
  datasource:
    url: jdbc:mysql://localhost:3306/stusys?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      initial-size: 10     #初始化连接池大小
      min-idle: 10         #最小大小
      max-active: 50       #最大大小
      max-wait: 60000      #获取连接时最大等待时间，单位毫秒
      time-between-eviction-runs-millis: 60000   #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000     #配置一个连接在池中最小生存的时间，单位是毫秒
      validation-query: SELECT 1 FROM DUAL       #用来检测连接是否有效的sql
      test-while-idle: true                      #申请连接的时候检测，建议配置为true，不影响性能，并且保证安全性
      testOnBorrow: false                        #获取连接时执行检测，建议关闭，影响性能
      testOnReturn: false                        #归还连接时执行检测，建议关闭，影响性能
      pool-prepared-statements: false            #是否开启PSCache，PSCache对支持游标的数据库性能提升巨大，oracle建议开启，mysql下建议关闭
      filters: stat,wall                   #配置扩展插件，常用的插件有=>stat:监控统计  log4j:日志  wall:防御sql注入
      connection-properties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000   #打开慢sql记录和延迟时间
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: root
        login-password: root
        enabled: true
#  Tip:关于搭建好后，druid监控页面访问不到或登录不上一直报账号密码错误的问题。
# （1）首先看能不能正常访问数据库，若不能访问数据库则说明没搭建成功
# （2）若能访问数据库，但是访问不到druid的登录页面，说明druid的版本可能和springboot不兼容，换个druid版本试试
# （3）存在登录不上的问题，但是账号密码都没错，检查服务器是否使用了权限框架，让权限框架放行/druid/*所有的请求

#redis常用配置
  redis:
    #数据库索引(默认为0)
    database: 0
    #服务器连接地址
    host: localhost
    #服务器连接端口
    port: 6379
    #连接超时时间(毫秒)
    timeout: 1800000
    lettuce:
      pool:
        #连接池最大连接数(使用负值表示没有限制)
        max-active: 20
        #最大阻塞等待时间(使用负值表示没有限制)
        max-wait: -1
        #连接池中的最大空闲连接
        max-idle: 5
        #连接池中的最小空闲连接
        min-idle: 0

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: cn.bdqn.entity

#配置sql打印日志
logging:
  level:
    com:
      looedu:
        mapper: debug

#pagehelper分页工具配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

server:
  port: 8081

jike:
  jwt:
    header: authorization
    expire: 604800 #7天 秒单位
    secret: dfhuiwkfsuu76374jfsjdgfsfrfd65fg

#管理监控指标
#management:
#  endpoints:
#    enabled-by-default: true #默认开启所有监控端点
#    web:
#      exposure:
#        include: '*' #以web方式暴露所有端点



