INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (1, '走进Java编程世界', 55, 1);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (2, 'HTML和CSS网页技术', 60, 1);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (3, 'C#语言和数据库技术', 70, 1);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (4, '使用C#语言开发数据库应用系统', 36, 1);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (5, '深入.NET平台和C#编程', 76, 2);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (6, '设计MySchool数据库', 42, 2);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (7, '基于.NET平台的软件系统分层开发', 44, 2);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (8, '面向对象程序设计', 59, 2);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (9, '使用JavaScript增强交互效果', 40, 2);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (10, '使用Java EE技术开发新闻发布系统', 55, 2);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (11, '使用ASP.NET技术开发网上书店', 86, 3);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (12, '开发基于Ajax和控件技术的Web应用系', 60, 3);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (13, '使用Java框架技术开发网上信息发布系统', 52, 3);
INSERT INTO stusys.subject (SubjectId, SubjectName, ClassHour, GradeId) VALUES (14, '使用Java企业级技术开发企业应用', 68, 3);